name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest,macos-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        name: Install Python
        with:
          python-version: '3.9'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.12.1

      - name: Build wheels
        env: 
          CIBW_BUILD: cp36-* cp37-* cp38-* cp39-* cp310-*
          CI_BEFORE_ALL_LINUX: sudo apt-get install gfortran
          CIBW_BEFORE_ALL_MACOS: brew install gcc && brew reinstall gfortran
          CIBW_BEFORE_BUILD: "pip install numpy"
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@3
        with:
          path: ./wheelhouse/*.whl
