name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            cibw_archs: "native"
          - os: ubuntu-22.04
            cibw_archs: "aarch64"
          - os: windows-latest
            cibw_archs: "native ARM64"
          - os: macos-latest
            cibw_archs: "native arm64"

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.9'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.12.1

      - name: Build wheels
        env: 
          CIBW_BUILD: cp39-* cp310-* cp311-*
          CI_BEFORE_ALL_LINUX: sudo apt-get install gfortran
          CIBW_BEFORE_ALL_MACOS: brew install gcc && brew reinstall gfortran
          CIBW_BEFORE_BUILD: "pip install numpy"
          CIBW_ARCHS_MACOS: x86_64 arm64
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
